# Generated by Django 4.1.3 on 2022-11-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_post"),
    ]

    operations = [
        migrations.RenameModel(old_name="Person", new_name="Author",),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.author"
                    ),
                ),
            ],
        ),
    ]
